import Transaction from "../models/Transaction.js";
import Worker from "../models/Worker.js";
import WorkerProject from "../models/WorkerProject.js";
import Week from "../models/Week.js";
import { calc, transactionTotals } from "../utils/calc.js";
import { monthRange, today } from "../utils/date.js";
import { requireProjectId } from "../utils/project.js";
const MONTHS_AR=["يناير","فبراير","مارس","أبريل","مايو","يونيو","يوليو","أغسطس","سبتمبر","أكتوبر","نوفمبر","ديسمبر"];
function future(y,m){const n=new Date(`${today()}T00:00:00Z`);return new Date(Date.UTC(y,m-1,1))>new Date(Date.UTC(n.getUTCFullYear(),n.getUTCMonth(),1));}
async function data(projectId,year,month){const mr=monthRange(year,month);if(!mr)throw Object.assign(new Error("Invalid month"),{statusCode:400,code:"INVALID_MONTH"});if(future(mr.year,mr.month))throw Object.assign(new Error("Future months cannot be searched"),{statusCode:400,code:"FUTURE_MONTH_NOT_ALLOWED"});const weeks=await Week.find({projectId,weekEnd:{$gte:mr.start},weekStart:{$lt:mr.end}}).lean();if(!weeks.length)throw Object.assign(new Error("Month is not available in database"),{statusCode:404,code:"MONTH_NOT_FOUND"});const txs=await Transaction.find({projectId,date:{$gte:mr.start,$lt:mr.end}}).lean();const ids=new Set();weeks.forEach(w=>w.workers.forEach(e=>{ids.add(e.workerId.toString())}));txs.forEach(t=>ids.add(t.workerId.toString()));const workers=await Worker.find({_id:{$in:[...ids]}}).sort({name:1}).lean();const rows=workers.map(w=>{const md=weeks.flatMap(week=>{const e=week.workers.find(x=>x.workerId.toString()===w._id.toString());return (e?.days||[]).filter(d=>d.date>=mr.start&&d.date<mr.end)});const a=calc(md),t=transactionTotals(txs.filter(x=>x.workerId.toString()===w._id.toString())),due=a.net+a.overtime+t.rewards-t.deductions;return{id:w._id,name:w.name,attendance:{presentDays:a.presentDays,absentDays:a.absentDays,grossEarned:a.gross,dailyDeductions:a.deductions,overtime:a.overtime},financial:{rewards:t.rewards,transactionDeductions:t.deductions,totalDiscounts:a.deductions+t.deductions,totalDue:due,paid:t.payments,remaining:due-t.payments}}});const summary=rows.reduce((s,r)=>{s.totalDue+=r.financial.totalDue;s.totalPaid+=r.financial.paid;s.totalRemaining+=r.financial.remaining;s.totalWorkers++;s.totalPresentDays+=r.attendance.presentDays;s.totalAbsentDays+=r.attendance.absentDays;s.totalDiscounts+=r.financial.totalDiscounts;s.totalRewards+=r.financial.rewards;s.totalOvertime+=r.attendance.overtime;return s;},{totalDue:0,totalPaid:0,totalRemaining:0,totalWorkers:0,totalPresentDays:0,totalAbsentDays:0,totalDiscounts:0,totalRewards:0,totalOvertime:0});return{month:{year:mr.year,month:mr.month,monthName:MONTHS_AR[mr.month-1],startDate:mr.start,endDate:new Date(Date.UTC(mr.year,mr.month,0)).toISOString().slice(0,10)},summary,workers:rows};}
export async function summary(req,res,next){try{const p=requireProjectId(req),now=new Date(),y=req.query.year===undefined?now.getUTCFullYear():Number(req.query.year),m=req.query.month===undefined?now.getUTCMonth()+1:Number(req.query.month);res.json({success:true,data:await data(p,y,m)});}catch(e){next(e);}}
export async function project(req,res,next){try{const p=requireProjectId(req);const weeks=await Week.find({projectId:p}).lean(),txs=await Transaction.find({projectId:p}).lean(),workers=await Worker.find({_id:{$in:[...new Set(weeks.flatMap(w=>w.workers.map(e=>e.workerId.toString())))]}}).sort({name:1}).lean();const rows=workers.map(w=>{const ds=weeks.flatMap(week=>{const e=week.workers.find(x=>x.workerId.toString()===w._id.toString());return (e?.days||[])}),a=calc(ds),t=transactionTotals(txs.filter(x=>x.workerId.toString()===w._id.toString())),due=a.net+a.overtime+t.rewards-t.deductions;return{id:w._id,name:w.name,attendance:{presentDays:a.presentDays,absentDays:a.absentDays,grossEarned:a.gross,dailyDeductions:a.deductions,overtime:a.overtime},financial:{rewards:t.rewards,transactionDeductions:t.deductions,totalDue:due,paid:t.payments,remaining:due-t.payments}}});res.json({success:true,data:{projectId:p,summary:rows.reduce((s,r)=>{s.totalDue+=r.financial.totalDue;s.totalPaid+=r.financial.paid;s.totalRemaining+=r.financial.remaining;s.totalGrossEarned+=r.attendance.grossEarned;s.totalDailyDeductions+=r.attendance.dailyDeductions;s.totalOvertime+=r.attendance.overtime;s.totalTransactionDeductions+=r.financial.transactionDeductions;s.totalRewards+=r.financial.rewards;s.totalOvertime+=r.attendance.overtime;s.totalWorkers++;return s;},{totalDue:0,totalPaid:0,totalRemaining:0,totalGrossEarned:0,totalDailyDeductions:0,totalTransactionDeductions:0,totalRewards:0,totalWorkers:0}),workers:rows,weeksCount:weeks.length,transactionsCount:txs.length}});}catch(e){next(e);}}
