import Transaction from "../models/Transaction.js";
import Worker from "../models/Worker.js";
import WorkerProject from "../models/WorkerProject.js";
import Week from "../models/Week.js";
import { date, today, isFuture, range } from "../utils/date.js";
import { requireProjectId } from "../utils/project.js";

const TYPES=["deduction","reward","payment"];
function positive(v){return v!==undefined&&v!==null&&String(v).trim()!==""&&Number.isFinite(Number(v))&&Number(v)>0;}
async function assertWeekOpen(projectId,targetDate){const r=range(targetDate);if(!r)throw Object.assign(new Error("Invalid date"),{statusCode:400,code:"INVALID_DATE"});const w=await Week.findOne({projectId,weekStart:r.weekStart});if(!w)throw Object.assign(new Error("Week is not available in database"),{statusCode:404,code:"WEEK_NOT_FOUND"});if(w.closed)throw Object.assign(new Error("Week is closed"),{statusCode:409,code:"WEEK_CLOSED"});return w;}

async function assertWeekExists(projectId,targetDate){const r=range(targetDate);if(!r)throw Object.assign(new Error("Invalid date"),{statusCode:400,code:"INVALID_DATE"});const w=await Week.findOne({projectId,weekStart:r.weekStart});if(!w)throw Object.assign(new Error("Week is not available in database"),{statusCode:404,code:"WEEK_NOT_FOUND"});return w;}
async function assertAssigned(projectId,workerId,targetDate){const a=await WorkerProject.findOne({projectId,workerId,effectiveFrom:{$lte:targetDate},$or:[{effectiveTo:null},{effectiveTo:{$gte:targetDate}}]});if(!a)throw Object.assign(new Error("Worker is not assigned to this project on this date"),{statusCode:409,code:"WORKER_NOT_ASSIGNED_ON_DATE"});return a;}
function wageTransactions(assignments){return assignments.flatMap(a=>a.wageHistory.map((w,i)=>({id:`wage-${a._id}-${i}`,projectId:a.projectId,workerId:a.workerId,type:"wage_change",amount:Number(w.amount),note:"تغيير اليومية",date:w.effectiveFrom,createdAt:w.effectiveFrom})));}

export async function add(req,res,next){try{const projectId=requireProjectId(req),workerId=req.params.id,type=String(req.body.type||""),amount=Number(req.body.amount),targetDate=String(req.body.date||today());if(!TYPES.includes(type)||!positive(req.body.amount)||!date(targetDate)||isFuture(targetDate))throw Object.assign(new Error("type, positive amount, and a non-future valid date are required"),{statusCode:400,code:"INVALID_TRANSACTION"});if(!(await Worker.exists({_id:workerId,projectId})))throw Object.assign(new Error("Worker not found in this project"),{statusCode:404,code:"WORKER_NOT_FOUND"});await assertAssigned(projectId,workerId,targetDate);await assertWeekExists(projectId,targetDate);const tx=await Transaction.create({projectId,workerId,type,amount,note:String(req.body.note??req.body.reason??"").trim(),date:targetDate});res.status(201).json({success:true,message:"تمت إضافة المعاملة بنجاح",data:tx});}catch(e){next(e);}}
export async function list(req,res,next){try{const projectId=requireProjectId(req),worker=await Worker.findOne({_id:req.params.id,projectId}).lean();if(!worker)throw Object.assign(new Error("Worker not found"),{statusCode:404,code:"WORKER_NOT_FOUND"});const assignments=await WorkerProject.find({projectId,workerId:worker._id}).sort({effectiveFrom:-1}).lean();if(!assignments.length)throw Object.assign(new Error("Worker is not assigned to this project"),{statusCode:404,code:"WORKER_NOT_IN_PROJECT"});const type=req.query.type; if(type&&![...TYPES,"wage_change","all"].includes(type))throw Object.assign(new Error("Invalid transaction type"),{statusCode:400,code:"INVALID_TRANSACTION_TYPE"});const real=await Transaction.find({projectId,workerId:worker._id,...(type&&type!=="all"&&type!=="wage_change"?{type}:{})}).sort({date:-1,createdAt:-1}).lean();const wage=wageTransactions(assignments);const transactions=[...real,...((!type||type==="all"||type==="wage_change")?wage:[])].filter(t=>!type||type==="all"||t.type===type).sort((a,b)=>String(b.date).localeCompare(String(a.date))||String(b.createdAt||"").localeCompare(String(a.createdAt||"")));res.json({success:true,data:transactions});}catch(e){next(e);}}
export async function update(req,res,next){try{const projectId=requireProjectId(req),existing=await Transaction.findOne({_id:req.params.id,projectId});if(!existing)throw Object.assign(new Error("Transaction not found"),{statusCode:404,code:"TRANSACTION_NOT_FOUND"});const targetDate=req.body.date!==undefined?String(req.body.date):existing.date;if(!date(targetDate)||isFuture(targetDate))throw Object.assign(new Error("Invalid date"),{statusCode:400,code:"INVALID_DATE"});await assertWeekOpen(projectId,existing.date);if(targetDate!==existing.date){await assertAssigned(projectId,existing.workerId,targetDate);await assertWeekOpen(projectId,targetDate);}if(req.body.amount!==undefined){if(!positive(req.body.amount))throw Object.assign(new Error("Amount must be greater than zero"),{statusCode:400,code:"INVALID_AMOUNT"});existing.amount=Number(req.body.amount);}if(req.body.note!==undefined||req.body.reason!==undefined)existing.note=String(req.body.note??req.body.reason).trim();if(req.body.date!==undefined)existing.date=targetDate;if(req.body.type!==undefined){if(!TYPES.includes(req.body.type))throw Object.assign(new Error("Invalid transaction type"),{statusCode:400,code:"INVALID_TRANSACTION_TYPE"});existing.type=req.body.type;}await existing.save();res.json({success:true,message:"تم تعديل المعاملة بنجاح",data:existing});}catch(e){next(e);}}
export async function remove(req,res,next){try{const projectId=requireProjectId(req),tx=await Transaction.findOne({_id:req.params.id,projectId});if(!tx)throw Object.assign(new Error("Transaction not found"),{statusCode:404,code:"TRANSACTION_NOT_FOUND"});await assertWeekOpen(projectId,tx.date);await tx.deleteOne();res.json({success:true,message:"تم حذف المعاملة بنجاح",data:{id:req.params.id}});}catch(e){next(e);}}
