import Worker from "../models/Worker.js";
import Week from "../models/Week.js";
import { calc } from "../utils/calc.js";
import { days, dayNameArabic, today, date, isFuture, range } from "../utils/date.js";
import { requireProjectId } from "../utils/project.js";
import { currentWeek, getWeek, requireExistingWeek } from "../utils/weekService.js";

function error(code,message,statusCode=400){return Object.assign(new Error(message),{code,statusCode});}
function serializeWeek(week,workers){const map=new Map(workers.map(w=>[w._id.toString(),w]));const rows=week.workers.filter(e=>!e.deleted).map(e=>{const w=map.get(e.workerId.toString());return w?{worker:w,days:e.days,summary:calc(e.days)}:null}).filter(Boolean);const summary=rows.reduce((s,r)=>{s.gross+=r.summary.gross;s.deductions+=r.summary.deductions;s.net+=r.summary.net;s.overtime+=r.summary.overtime;s.totalEarned+=r.summary.totalEarned;s.presentDays+=r.summary.presentDays;s.absentDays+=r.summary.absentDays;return s},{gross:0,deductions:0,net:0,overtime:0,totalEarned:0,presentDays:0,absentDays:0});return{week:{id:week._id,startDate:week.weekStart,endDate:week.weekEnd,closed:week.closed,projectId:week.projectId},days:days(week.weekStart).map(d=>({date:d,dayName:dayNameArabic(d)})),workers:rows,summary};}
async function send(res,week){const workers=await Worker.find({_id:{$in:week.workers.map(x=>x.workerId)}}).lean();res.json({success:true,data:serializeWeek(week,workers)});}
export async function showByDate(req,res,next){try{const p=requireProjectId(req),target=req.params.date;if(!date(target))throw error("INVALID_DATE","Invalid date");if(isFuture(target))throw error("FUTURE_DATE_NOT_ALLOWED","Future dates cannot be searched");await send(res,await requireExistingWeek(p,target));}catch(e){next(e);}}
export async function current(req,res,next){try{await send(res,await currentWeek(requireProjectId(req)));}catch(e){next(e);}}
export async function previous(req,res,next){try{const p=requireProjectId(req),requested=req.query.from||today(),base=await requireExistingWeek(p,requested),d=new Date(`${base.weekStart}T00:00:00.000Z`);d.setUTCDate(d.getUTCDate()-7);await send(res,await requireExistingWeek(p,d.toISOString().slice(0,10)));}catch(e){next(e);}}
export async function next(req,res,next){try{const p=requireProjectId(req),requested=req.query.from||today(),base=await requireExistingWeek(p,requested),d=new Date(`${base.weekStart}T00:00:00.000Z`);d.setUTCDate(d.getUTCDate()+7);const nextStart=d.toISOString().slice(0,10),current=await currentWeek(p);if(nextStart>current.weekStart)throw error("NO_FUTURE_WEEK","No future week available",409);await send(res,await requireExistingWeek(p,nextStart));}catch(e){next(e);}}
export async function toggleClose(req,res,next){try{const p=requireProjectId(req),week=await Week.findOne({_id:req.params.id,projectId:p});if(!week)throw error("WEEK_NOT_FOUND","Week not found",404);week.closed=!week.closed;await week.save();res.json({success:true,message:week.closed?"تم إغلاق الأسبوع بنجاح":"تم فتح الأسبوع بنجاح",data:{week:{id:week._id,projectId:p,startDate:week.weekStart,endDate:week.weekEnd,closed:week.closed}}});}catch(e){next(e);}}
export async function archive(req,res,next){try{const p=requireProjectId(req),target=String(req.query.date||"");if(!date(target))throw error("INVALID_DATE","A valid date is required");if(isFuture(target))throw error("FUTURE_DATE_NOT_ALLOWED","Future dates cannot be searched");const week=await requireExistingWeek(p,target),workers=await Worker.find({_id:{$in:week.workers.map(x=>x.workerId)}}).lean();let payload=serializeWeek(week,workers);const q=String(req.query.q||"").trim().toLowerCase();if(q)payload.workers=payload.workers.filter(r=>r.worker.name.toLowerCase().includes(q));payload.summary=payload.workers.reduce((s,r)=>{s.gross+=r.summary.gross;s.deductions+=r.summary.deductions;s.net+=r.summary.net;s.overtime+=r.summary.overtime;s.totalEarned+=r.summary.totalEarned;s.presentDays+=r.summary.presentDays;s.absentDays+=r.summary.absentDays;return s},{gross:0,deductions:0,net:0,overtime:0,totalEarned:0,presentDays:0,absentDays:0});res.json({success:true,data:payload});}catch(e){next(e);}}
